name: cloudbeaver
services:
    cloudbeaver:
        container_name: cloudbeaver
        deploy:
            resources:
                reservations:
                    memory: "268435456"
        image: dbeaver/cloudbeaver:26.0.5@sha256:c9dd1cbc23c0c20c16c4d5092b52135d6de16fa4a7cef7f5a97ad5a5abf19716
        labels:
            icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.cloudbeaver/assets/icon.svg
        network_mode: bridge
        ports:
            - target: 8978
              published: "8978"
              protocol: tcp
        restart: unless-stopped
        volumes:
            - type: bind
              source: ${APPDATA_ROOT}/cloudbeaver/workspace
              target: /opt/cloudbeaver/workspace
x-casaos:
    icon: https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@gh-pages/apps/org.icewhale.cloudbeaver/assets/icon.svg
    id: org.icewhale.cloudbeaver
    index: /
    is_uncontrolled: false
    main: cloudbeaver
    port_map: "8978"
    repo_id: zimaos-appstore
    store_app_id: cloudbeaver
    title:
        en_US: CloudBeaver
        pt_BR: CloudBeaver
    version: 26.0.5
